// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAJlrfE5u3b-HEYjrk6FVNRWhXyA1frXM',
    appId: '1:448176694087:web:d8ca86c1147e877fcee262',
    messagingSenderId: '448176694087',
    projectId: 'chat-app-88fd7',
    authDomain: 'chat-app-88fd7.firebaseapp.com',
    storageBucket: 'chat-app-88fd7.firebasestorage.app',
    measurementId: 'G-XHKXWVSD4K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI5cwvK5oROHj62xS50qROgKiFpS_JBrI',
    appId: '1:448176694087:android:dac1db0844568c9bcee262',
    messagingSenderId: '448176694087',
    projectId: 'chat-app-88fd7',
    storageBucket: 'chat-app-88fd7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5lFXqVGmVtxGTOU4yUInkUYBLJ_ooA0M',
    appId: '1:448176694087:ios:91f6f1aae436bf48cee262',
    messagingSenderId: '448176694087',
    projectId: 'chat-app-88fd7',
    storageBucket: 'chat-app-88fd7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5lFXqVGmVtxGTOU4yUInkUYBLJ_ooA0M',
    appId: '1:448176694087:ios:91f6f1aae436bf48cee262',
    messagingSenderId: '448176694087',
    projectId: 'chat-app-88fd7',
    storageBucket: 'chat-app-88fd7.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAJlrfE5u3b-HEYjrk6FVNRWhXyA1frXM',
    appId: '1:448176694087:web:f8e0af1c1e3ca07bcee262',
    messagingSenderId: '448176694087',
    projectId: 'chat-app-88fd7',
    authDomain: 'chat-app-88fd7.firebaseapp.com',
    storageBucket: 'chat-app-88fd7.firebasestorage.app',
    measurementId: 'G-Z7NF7CLB6J',
  );
}
